# Pandas
   - Library OF Python use to analye and modified data

# Pandas
    - pd.series  is 1d series it has only one coloum
    - pd.dataframe its has more then one coloum and its called 2d series

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series(['Apples', 'Banana', 'Guava', 'Kiwi', 'Pineapple', 'Watermelon'], name="Fruits", index=[1,2,3,4,5,6])
s1

1        Apples
2        Banana
3         Guava
4          Kiwi
5     Pineapple
6    Watermelon
Name: Fruits, dtype: object

In [3]:
s1[1]

'Apples'

In [27]:
s1.iloc[1]   #iloc use default index to acces values which is start from 0

'Banana'

In [29]:
s1.loc[1]   #loc is used to acces srting index values but also string index vlaues acces by normal method which is s["name_string_index"]

'Apples'

In [6]:
s1.values

array(['Apples', 'Banana', 'Guava', 'Kiwi', 'Pineapple', 'Watermelon'],
      dtype=object)

In [7]:
s2 = pd.Series(index = ['Apples', 'Banana', 'Guava', 'Kiwi', 'Pineapple', 'Watermelon'], name="Fruits", data=[11,25,37,48,59,60])
s2

Apples        11
Banana        25
Guava         37
Kiwi          48
Pineapple     59
Watermelon    60
Name: Fruits, dtype: int64

In [8]:
s2['Apples']

np.int64(11)

In [9]:
s2.iloc[0]

np.int64(11)

In [10]:
s2.loc['Apples']

np.int64(11)

In [11]:
s2.values

array([11, 25, 37, 48, 59, 60])

In [12]:
s2.keys

<bound method Series.keys of Apples        11
Banana        25
Guava         37
Kiwi          48
Pineapple     59
Watermelon    60
Name: Fruits, dtype: int64>

In [13]:
s2['Potato'] = [23]

# DataFrame
   - data frame contain more then 1 coloum and it is called 2d
   - data frame give clean ui when we load date through pd.dataframe()

In [23]:
s3 = pd.DataFrame({"name":["hazzan","ali","ilyas","ilaqat","zubair","abdullah","saad","azaan","haider","haya"],
             "pandas":[67,89,90,87,65,45,34,78,90,99],
             "statistics":[89,78,67,89,56,45,36,87,90,90],
             "python":[56,67,87,97,35,67,46,75,75,65],
             "reputation":["good","bad","normal","good","bad","normal","good","bad","normal","bad"],
            })

s3

       name  pandas  statistics  python reputation
0    hazzan      67          89      56       good
1       ali      89          78      67        bad
2     ilyas      90          67      87     normal
3    ilaqat      87          89      97       good
4    zubair      65          56      35        bad
5  abdullah      45          45      67     normal
6      saad      34          36      46       good
7     azaan      78          87      75        bad
8    haider      90          90      75     normal
9      haya      99          90      65        bad

In [30]:
#mrthod 1 to add
s3['Total_Mark'] = s3['statistics']+s3['python']+s3["pandas"]
#method 2 to add
s3['Total_Mark_2'] = s3.statistics+s3.python+s3.pandas

In [31]:
s3

,name,pandas,statistics,python,reputation,Total_Marks,Total_Mark,Total_Mark_2
0,hazzan,67,89,56,good,212,212,212
1,ali,89,78,67,bad,234,234,234
2,ilyas,90,67,87,normal,244,244,244
3,ilaqat,87,89,97,good,273,273,273
4,zubair,65,56,35,bad,156,156,156
5,abdullah,45,45,67,normal,157,157,157
6,saad,34,36,46,good,116,116,116
7,azaan,78,87,75,bad,240,240,240
8,haider,90,90,75,normal,255,255,255
9,haya,99,90,65,bad,254,254,254

In [44]:
s3["percentage"] = round(s3.Total_Mark_2/300*100,2)

In [45]:
s3

,name,pandas,statistics,python,reputation,Total_Mark,Total_Mark_2,percentage
0,hazzan,67,89,56,good,212,212,70.67
1,ali,89,78,67,bad,234,234,78.00
2,ilyas,90,67,87,normal,244,244,81.33
3,ilaqat,87,89,97,good,273,273,91.00
4,zubair,65,56,35,bad,156,156,52.00
5,abdullah,45,45,67,normal,157,157,52.33
6,saad,34,36,46,good,116,116,38.67
7,azaan,78,87,75,bad,240,240,80.00
8,haider,90,90,75,normal,255,255,85.00
9,haya,99,90,65,bad,254,254,84.67

In [70]:
#method one to add Grade in data frame
#List Comprehension simpel formula for list comprehension [what_if true if condition else another contition/value for dash in dah.dash]
s3["Grade_1"] = ["A+" if per>=90 
                else 
                   "A" if per>=80 
                else
                    "B" if per>=70 
                else
                   "C" if per>=40 
                else
                   "D" if per >=33
                else "F"
                             for per in s3.percentage]

In [71]:
s3

,name,pandas,statistics,python,reputation,Total_Mark,Total_Mark_2,percentage,Grade_1
0,hazzan,67,89,56,good,212,212,70.67,B
1,ali,89,78,67,bad,234,234,78.00,B
2,ilyas,90,67,87,normal,244,244,81.33,A
3,ilaqat,87,89,97,good,273,273,91.00,A+
4,zubair,65,56,35,bad,156,156,52.00,C
5,abdullah,45,45,67,normal,157,157,52.33,C
6,saad,34,36,46,good,116,116,38.67,D
7,azaan,78,87,75,bad,240,240,80.00,A
8,haider,90,90,75,normal,255,255,85.00,A
9,haya,99,90,65,bad,254,254,84.67,A

In [76]:
#mrthod two to add grade in data frame 
#lambda function is a anonymus function which have no name it create in one line and also destry after finish
s3['Grade_2'] = s3.percentage.apply(lambda per: "A+" if per>=90 else "A" if per>=80 else "B" if per>=70 else "C" if per>=50 else "D" if per>=33 else "F")

In [77]:
s3

,name,pandas,statistics,python,reputation,Total_Mark,Total_Mark_2,percentage,Grade_1,Grade_2
0,hazzan,67,89,56,good,212,212,70.67,B,B
1,ali,89,78,67,bad,234,234,78.00,B,B
2,ilyas,90,67,87,normal,244,244,81.33,A,A
3,ilaqat,87,89,97,good,273,273,91.00,A+,A+
4,zubair,65,56,35,bad,156,156,52.00,C,C
5,abdullah,45,45,67,normal,157,157,52.33,C,C
6,saad,34,36,46,good,116,116,38.67,D,D
7,azaan,78,87,75,bad,240,240,80.00,A,A
8,haider,90,90,75,normal,255,255,85.00,A,A
9,haya,99,90,65,bad,254,254,84.67,A,A

In [78]:
#mrthod three to add grade in data frame
#which is create a outline function and give there name series

def grade_calc(per):
    if per>= 90:
        return "A+"
    elif per>= 80:
        return "A"
    elif per >= 70:
        return "B"
    elif per>= 50:
        return "C"
    elif per>= 33:
        return "D"
    else:
        "F"

In [79]:
s3["Grade_3"] = s3.percentage.apply(grade_calc)

In [81]:
s3

,name,pandas,statistics,python,reputation,Total_Mark,Total_Mark_2,percentage,Grade_1,Grade_2,Grade_3
0,hazzan,67,89,56,good,212,212,70.67,B,B,B
1,ali,89,78,67,bad,234,234,78.00,B,B,B
2,ilyas,90,67,87,normal,244,244,81.33,A,A,A
3,ilaqat,87,89,97,good,273,273,91.00,A+,A+,A+
4,zubair,65,56,35,bad,156,156,52.00,C,C,C
5,abdullah,45,45,67,normal,157,157,52.33,C,C,C
6,saad,34,36,46,good,116,116,38.67,D,D,D
7,azaan,78,87,75,bad,240,240,80.00,A,A,A
8,haider,90,90,75,normal,255,255,85.00,A,A,A
9,haya,99,90,65,bad,254,254,84.67,A,A,A